# Vocal Remover Model Configuration

# Model Architecture
model:
  name: "UNetVocalRemover"
  input_channels: 2  # stereo input
  output_channels: 2  # stereo output
  hidden_channels: 64
  num_layers: 6
  kernel_size: 3
  stride: 2

# Audio Processing
audio:
  sample_rate: 44100
  n_fft: 2048
  hop_length: 512
  win_length: 2048
  chunk_duration: 10.0  # seconds
  overlap: 0.25  # 25% overlap between chunks

# Training Parameters
training:
  batch_size: 8
  learning_rate: 0.001
  num_epochs: 100
  patience: 10  # early stopping patience
  validation_split: 0.2
  save_every: 10  # save model every N epochs
  
# Loss Function
loss:
  type: "spectral_convergence"  # or "l1", "mse", "combined"
  alpha: 1.0  # weight for spectral convergence
  beta: 0.1   # weight for magnitude loss

# Data Augmentation
augmentation:
  enabled: true
  pitch_shift_range: [-2, 2]  # semitones
  time_stretch_range: [0.9, 1.1]
  noise_factor: 0.01

# Model Deployment
deployment:
  github:
    enabled: false
    repo_url: ""
    branch: "main"
  huggingface:
    enabled: false
    repo_id: ""
    token: ""  # set via environment variable HF_TOKEN

# Paths
paths:
  data_dir: "data"
  output_dir: "output"
  models_dir: "models"
  logs_dir: "logs"